name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the HarborGate master image
      run: docker build . --file Dockerfile --tag harborgate-master:ci
    - name: Build the HarborGate child image
      run: docker build . --file Dockerfile.child --tag harborgate-child:ci
